# Book settings
# Learn more at https://jupyterbook.org/customize/config.html



title: OpenMDAO
author: The OpenMDAO Development Team
logo: OpenMDAO_Logo.png
exclude_patterns : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", "template.ipynb"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  stderr_output: show
  allow_errors: false
  timeout: 300

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/OpenMDAO/OpenMDAO  # Online location of your book
  path_to_book: openmdao/docs/openmdao_book  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# Enable use of latex math
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - colon_fence
    - dollarmath
    - linkify
    - substitution

launch_buttons:
  colab_url: "https://colab.research.google.com"

# Enable use of sphinx autodoc
sphinx:
  config:
    html_baseurl: 'https://openmdao.org/newdocs/versions/latest/'
    sitemap_filename: 'sitemap.xml'
    html_theme: 'om-theme'
    html_theme_path: ['.'] # make sphinx search for themes in current dir
    html_theme_options:
      # WARNING: The default value for `navigation_with_keys` will change to `False` in the next release.
      # If you wish to preserve the old behavior for your site, set `navigation_with_keys=True` in the
      # `html_theme_options` dict in your `conf.py` file. Be aware that `navigation_with_keys = True` has
      # negative accessibility implications: https://github.com/pydata/pydata-sphinx-theme/issues/1492
      'navigation_with_keys': False

  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.autosummary'
  - 'sphinx.ext.viewcode'
  - 'sphinx_sitemap'
  - 'numpydoc'

